#!/usr/bin/bash

FILES=~/Documents/Jaily/nrlBPF/output/*
TOOL_DIR=~/Documents/Jaily/Toolchain

cd $TOOL_DIR

for file in $FILES
do
	_build/coton.native --convert_labelled_to_symbolic --absolute_jump_offsets $file > file1
	_build/coton.native --convert_symbolic_to_C file1 --absolute_jump_offsets > generated.c
	make harness
	./harness -i fuzz.pcap > file2
	#rm file1 file2
	echo "\n>>>\tCompleted Successfully"
done

#TC_DIR=~/Downloads/hook/
#IN_TXT=experiment/transpiler.txt

#cd $TC_DIR

#_build/coton.native --convert_labelled_to_symbolic $IN_TXT > file1
#_build/coton.native --convert_symbolic_to_C --absolute_jump_offsets file1 > generated.c
#make harness
#./harness -i fuzz.pcap > file2
#rm file1 file2
#echo "\n>>>\tCompleted Successfully"


