/* generated by Coton version 0.10 alpha
   Invocation: ./coton.native --absolute_jump_offsets --hex_numbers --convert_symbolic_to_C examples/mohammad_example3.symbolic
   At: 17:25:40 (UTC 21h28d) 2022/7/28 */
STEP ("Packet processing start");
l0: STEP ("Line 1");
accumulator = 0x0;
memcpy (((char *)&accumulator) + (0x0 + 0x1), ((char *)packet) + (0xc + 0x0), 0x1);
memcpy (((char *)&accumulator) + (0x0 + 0x0), ((char *)packet) + (0xc + 0x1), 0x1); // End of Line 1: ldh [0xc]
l1: STEP ("Line 2");
if (accumulator == 0x800) {
  STEP ("Line 2: True");
  goto l2;
} else {
  STEP ("Line 2: False");
  goto l5;
} // End of Line 2: jeq #0x800 jt 2 jf 5
l2: STEP ("Line 3");
accumulator = 0xff; // End of Line 3: ld #0xff
l3: STEP ("Line 4");
idx_register = 0x1a; // End of Line 4: ldx #0x1a
l4: STEP ("Line 5");
memcpy (((char *)packet) + (idx_register + 0x0), &accumulator, 0x1); // End of Line 5: stb [x+0x0]
l5: STEP ("Line 6");
DUMP ();
return (0x40000); // End of Line 6: ret #0x40000
l6: STEP ("Line 7");
DUMP ();
return (0x0); // End of Line 7: ret #0x0
