/* generated by Coton version 0.11 alpha
   Invocation: ./coton.native --absolute_jump_offsets --hex_numbers --convert_symbolic_to_C /dev/fd/63
   At: 16:12:23 (UTC 20h30d) 2022/7/30 */
STEP ("Packet processing start");
l0: STEP ("Line 1");
accumulator = 0x0;
memcpy (((char *)&accumulator) + (0x0 + 0x1), ((char *)packet) + (0xc + 0x0), 0x1);
memcpy (((char *)&accumulator) + (0x0 + 0x0), ((char *)packet) + (0xc + 0x1), 0x1); // End of Line 1: ldh [0xc]
l1: STEP ("Line 2");
if (accumulator == 0x800) {
  STEP ("Line 2: True");
  goto l2;
} else {
  STEP ("Line 2: False");
  goto l8;
} // End of Line 2: jeq #0x800 jt 2 jf 8
l2: STEP ("Line 3");
accumulator = 0xa24e003; // End of Line 3: ld #0xa24e003
l3: STEP ("Line 4");
idx_register = 0x1a; // End of Line 4: ldx #0x1a
l4: STEP ("Line 5");
hook (packet, "dump"); // End of Line 5: ?dump
l5: STEP ("Line 6");
memcpy (((char *)packet) + (idx_register + 0x0), &accumulator, 0x1); // End of Line 6: stb [x+0x0]
l6: STEP ("Line 7");
accumulator = 0x0;
memcpy (((char *)&accumulator) + (0x0 + 0x3), ((char *)packet) + (0x1a + 0x0), 0x1);
memcpy (((char *)&accumulator) + (0x0 + 0x2), ((char *)packet) + (0x1a + 0x1), 0x1);
memcpy (((char *)&accumulator) + (0x0 + 0x1), ((char *)packet) + (0x1a + 0x2), 0x1);
memcpy (((char *)&accumulator) + (0x0 + 0x0), ((char *)packet) + (0x1a + 0x3), 0x1); // End of Line 7: ld [0x1a]
l7: STEP ("Line 8");
hook (packet, "dump"); // End of Line 8: ?dump
l8: STEP ("Line 9");
DUMP ();
return (0x40000); // End of Line 9: ret #0x40000
l9: STEP ("Line 10");
DUMP ();
return (0x0); // End of Line 10: ret #0x0
