/* generated by Coton version 0.12 alpha
   Invocation: _build/coton.native --convert_symbolic_to_C file1 --absolute_jump_offsets
   At: 20:41:6 (UTC 20h4d) 2022/9/4 */
STEP ("Packet processing start");
l0: STEP ("Line 1");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 1: ldh [12]
l1: STEP ("Line 2");
if (accumulator == 2048) {
  STEP ("Line 2: True");
  goto l2;
} else {
  STEP ("Line 2: False");
  goto l4;
} // End of Line 2: jeq #2048 jt 2 jf 4
l2: STEP ("Line 3");
accumulator = 0;
memcpy (((char *)&accumulator) + 0, packet + 23, 1); // End of Line 3: ldb [23]
l3: STEP ("Line 4");
if (accumulator == 6) {
  STEP ("Line 4: True");
  goto l9;
} else {
  STEP ("Line 4: False");
  goto l52;
} // End of Line 4: jeq #6 jt 9 jf 52
l4: STEP ("Line 5");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 5: ldh [12]
l5: STEP ("Line 6");
if (accumulator == 34525) {
  STEP ("Line 6: True");
  goto l6;
} else {
  STEP ("Line 6: False");
  goto l8;
} // End of Line 6: jeq #34525 jt 6 jf 8
l6: STEP ("Line 7");
accumulator = 0;
memcpy (((char *)&accumulator) + 0, packet + 20, 1); // End of Line 7: ldb [20]
l7: STEP ("Line 8");
if (accumulator == 6) {
  STEP ("Line 8: True");
  goto l9;
} else {
  STEP ("Line 8: False");
  goto l52;
} // End of Line 8: jeq #6 jt 9 jf 52
l8: STEP ("Line 9");
accumulator = accumulator + 0; // End of Line 9: add #0
l9: STEP ("Line 10");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 10: ldh [12]
l10: STEP ("Line 11");
if (accumulator == 2048) {
  STEP ("Line 11: True");
  goto l11;
} else {
  STEP ("Line 11: False");
  goto l13;
} // End of Line 11: jeq #2048 jt 11 jf 13
l11: STEP ("Line 12");
accumulator = 0;
memcpy (((char *)&accumulator) + 0, packet + 23, 1); // End of Line 12: ldb [23]
l12: STEP ("Line 13");
if (accumulator == 6) {
  STEP ("Line 13: True");
  goto l17;
} else {
  STEP ("Line 13: False");
  goto l30;
} // End of Line 13: jeq #6 jt 17 jf 30
l13: STEP ("Line 14");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 14: ldh [12]
l14: STEP ("Line 15");
if (accumulator == 34525) {
  STEP ("Line 15: True");
  goto l15;
} else {
  STEP ("Line 15: False");
  goto l17;
} // End of Line 15: jeq #34525 jt 15 jf 17
l15: STEP ("Line 16");
accumulator = 0;
memcpy (((char *)&accumulator) + 0, packet + 20, 1); // End of Line 16: ldb [20]
l16: STEP ("Line 17");
if (accumulator == 6) {
  STEP ("Line 17: True");
  goto l17;
} else {
  STEP ("Line 17: False");
  goto l30;
} // End of Line 17: jeq #6 jt 17 jf 30
l17: STEP ("Line 18");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 18: ldh [12]
l18: STEP ("Line 19");
if (accumulator == 34525) {
  STEP ("Line 19: True");
  goto l19;
} else {
  STEP ("Line 19: False");
  goto l23;
} // End of Line 19: jeq #34525 jt 19 jf 23
l19: STEP ("Line 20");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (28 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (28 + 1), 1); // End of Line 20: ldh [28]
l20: STEP ("Line 21");
idx_register = 28; // End of Line 21: ldx #28
l21: STEP ("Line 22");
accumulator = 3232235777; // End of Line 22: ld #3232235777
l22: STEP ("Line 23");
memcpy (((char *)packet) + ((idx_register + 0) + 3), ((char *)&accumulator) + (0 + 0), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 2), ((char *)&accumulator) + (0 + 1), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 1), ((char *)&accumulator) + (0 + 2), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 0), ((char *)&accumulator) + (0 + 3), 1); // End of Line 23: st [x+0]
l23: STEP ("Line 24");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 24: ldh [12]
l24: STEP ("Line 25");
if (accumulator == 2048) {
  STEP ("Line 25: True");
  goto l25;
} else {
  STEP ("Line 25: False");
  goto l29;
} // End of Line 25: jeq #2048 jt 25 jf 29
l25: STEP ("Line 26");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (26 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (26 + 1), 1); // End of Line 26: ldh [26]
l26: STEP ("Line 27");
idx_register = 26; // End of Line 27: ldx #26
l27: STEP ("Line 28");
accumulator = 3232235777; // End of Line 28: ld #3232235777
l28: STEP ("Line 29");
memcpy (((char *)packet) + ((idx_register + 0) + 3), ((char *)&accumulator) + (0 + 0), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 2), ((char *)&accumulator) + (0 + 1), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 1), ((char *)&accumulator) + (0 + 2), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 0), ((char *)&accumulator) + (0 + 3), 1); // End of Line 29: st [x+0]
l29: STEP ("Line 30");
accumulator = accumulator + 0; // End of Line 30: add #0
l30: STEP ("Line 31");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 31: ldh [12]
l31: STEP ("Line 32");
if (accumulator == 2048) {
  STEP ("Line 32: True");
  goto l32;
} else {
  STEP ("Line 32: False");
  goto l34;
} // End of Line 32: jeq #2048 jt 32 jf 34
l32: STEP ("Line 33");
accumulator = 0;
memcpy (((char *)&accumulator) + 0, packet + 23, 1); // End of Line 33: ldb [23]
l33: STEP ("Line 34");
if (accumulator == 6) {
  STEP ("Line 34: True");
  goto l38;
} else {
  STEP ("Line 34: False");
  goto l51;
} // End of Line 34: jeq #6 jt 38 jf 51
l34: STEP ("Line 35");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 35: ldh [12]
l35: STEP ("Line 36");
if (accumulator == 34525) {
  STEP ("Line 36: True");
  goto l36;
} else {
  STEP ("Line 36: False");
  goto l38;
} // End of Line 36: jeq #34525 jt 36 jf 38
l36: STEP ("Line 37");
accumulator = 0;
memcpy (((char *)&accumulator) + 0, packet + 20, 1); // End of Line 37: ldb [20]
l37: STEP ("Line 38");
if (accumulator == 6) {
  STEP ("Line 38: True");
  goto l38;
} else {
  STEP ("Line 38: False");
  goto l51;
} // End of Line 38: jeq #6 jt 38 jf 51
l38: STEP ("Line 39");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 39: ldh [12]
l39: STEP ("Line 40");
if (accumulator == 34525) {
  STEP ("Line 40: True");
  goto l40;
} else {
  STEP ("Line 40: False");
  goto l44;
} // End of Line 40: jeq #34525 jt 40 jf 44
l40: STEP ("Line 41");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (38 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (38 + 1), 1); // End of Line 41: ldh [38]
l41: STEP ("Line 42");
idx_register = 38; // End of Line 42: ldx #38
l42: STEP ("Line 43");
accumulator = 16885952; // End of Line 43: ld #16885952
l43: STEP ("Line 44");
memcpy (((char *)packet) + ((idx_register + 0) + 3), ((char *)&accumulator) + (0 + 0), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 2), ((char *)&accumulator) + (0 + 1), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 1), ((char *)&accumulator) + (0 + 2), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 0), ((char *)&accumulator) + (0 + 3), 1); // End of Line 44: st [x+0]
l44: STEP ("Line 45");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 45: ldh [12]
l45: STEP ("Line 46");
if (accumulator == 2048) {
  STEP ("Line 46: True");
  goto l46;
} else {
  STEP ("Line 46: False");
  goto l50;
} // End of Line 46: jeq #2048 jt 46 jf 50
l46: STEP ("Line 47");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (30 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (30 + 1), 1); // End of Line 47: ldh [30]
l47: STEP ("Line 48");
idx_register = 30; // End of Line 48: ldx #30
l48: STEP ("Line 49");
accumulator = 16885952; // End of Line 49: ld #16885952
l49: STEP ("Line 50");
memcpy (((char *)packet) + ((idx_register + 0) + 3), ((char *)&accumulator) + (0 + 0), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 2), ((char *)&accumulator) + (0 + 1), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 1), ((char *)&accumulator) + (0 + 2), 1);
memcpy (((char *)packet) + ((idx_register + 0) + 0), ((char *)&accumulator) + (0 + 3), 1); // End of Line 50: st [x+0]
l50: STEP ("Line 51");
accumulator = accumulator + 0; // End of Line 51: add #0
l51: STEP ("Line 52");
DUMP ();
return (262144); // End of Line 52: ret #262144
l52: STEP ("Line 53");
DUMP ();
return (0); // End of Line 53: ret #0
