/* generated by Coton version 0.12 alpha
   Invocation: _build/coton.native --convert_symbolic_to_C file1 --absolute_jump_offsets
   At: 13:11:0 (UTC 18h4d) 2022/9/4 */
STEP ("Packet processing start");
l0: STEP ("Line 1");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 1: ldh [12]
l1: STEP ("Line 2");
if (accumulator == 34525) {
  STEP ("Line 2: True");
  goto l2;
} else {
  STEP ("Line 2: False");
  goto l4;
} // End of Line 2: jeq #34525 jt 2 jf 4
l2: STEP ("Line 3");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (52 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (52 + 1), 1); // End of Line 3: ldh [52]
l3: STEP ("Line 4");
if (accumulator == 1072) {
  STEP ("Line 4: True");
  goto l9;
} else {
  STEP ("Line 4: False");
  goto l10;
} // End of Line 4: jeq #1072 jt 9 jf 10
l4: STEP ("Line 5");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (12 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (12 + 1), 1); // End of Line 5: ldh [12]
l5: STEP ("Line 6");
if (accumulator == 2048) {
  STEP ("Line 6: True");
  goto l6;
} else {
  STEP ("Line 6: False");
  goto l8;
} // End of Line 6: jeq #2048 jt 6 jf 8
l6: STEP ("Line 7");
accumulator = 0;
memcpy (((char *)&accumulator) + (0 + 1), ((char *)packet) + (32 + 0), 1);
memcpy (((char *)&accumulator) + (0 + 0), ((char *)packet) + (32 + 1), 1); // End of Line 7: ldh [32]
l7: STEP ("Line 8");
if (accumulator == 1072) {
  STEP ("Line 8: True");
  goto l9;
} else {
  STEP ("Line 8: False");
  goto l10;
} // End of Line 8: jeq #1072 jt 9 jf 10
l8: STEP ("Line 9");
accumulator = accumulator + 0; // End of Line 9: add #0
l9: STEP ("Line 10");
DUMP ();
return (262144); // End of Line 10: ret #262144
l10: STEP ("Line 11");
DUMP ();
return (0); // End of Line 11: ret #0
